#   ___  _           _  ______
#  / _ \| |         | | | ___ \
# / /_\ \ | ___ _ __| |_| |_/ / __ _____  ___   _
# |  _  | |/ _ \ '__| __|  __/ '__/ _ \ \/ / | | |
# | | | | |  __/ |  | |_| |  | | | (_) >  <| |_| |
# \_| |_/_|\___|_|   \__\_|  |_|  \___/_/\_\\__, |
#                    Alert-Proxy             __/ |
#                                           |___/
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alert-proxy.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alert-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    #   ___  _           _  ______
    #  / _ \| |         | | | ___ \
    # / /_\ \ | ___ _ __| |_| |_/ / __ _____  ___   _
    # |  _  | |/ _ \ '__| __|  __/ '__/ _ \ \/ / | | |
    # | | | | |  __/ |  | |_| |  | | | (_) >  <| |_| |
    # \_| |_/_|\___|_|   \__\_|  |_|  \___/_/\_\\__, |
    #                    Alert-Proxy             __/ |
    #                                           |___/
    # This file is generated by Helm chart. Do not edit directly.
    # WARNING: Storing sensitive data in ConfigMaps is generally not recommended for production environments
    # as ConfigMaps are not encrypted. Consider using Kubernetes Secrets directly via mounted files or envFrom.
    ---
    debug: {{ .Values.config.debug }}
    app_debug: {{ .Values.config.app_debug }}
    # Logging
    logging:
      log_level: '{{ .Values.config.logging.log_level }}'
      log_dir: '{{ .Values.config.logging.log_dir }}'
      log_file_name: '{{ .Values.config.logging.log_file_name }}'
    alert_proxy_config:
      log_level: '{{ .Values.config.alert_proxy_config.log_level }}'
      alert_verification: {{ .Values.config.alert_proxy_config.alert_verification }}
      # Secrets are now sourced from environment variables injected by the Deployment.
      core_account_id: "${CORE_ACCOUNT_NUMBER}"
      core_overseer_id: "${OVERSEER_CORE_DEVICE_ID}"
      account_secret: "${ACCOUNT_SERVICE_TOKEN}"
      am_v2_base_url: "${ALERT_MANAGER_BASE_URL}"
