apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alert-proxy.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alert-proxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    # This file is generated by Helm chart. Do not edit directly.
    # WARNING: Storing sensitive data in ConfigMaps is generally not recommended for production environments
    # as ConfigMaps are not encrypted. Consider using Kubernetes Secrets directly via mounted files or envFrom.
    ---
    debug: {{ .Values.config.debug }}
    app_debug: {{ .Values.config.app_debug }}
    logging:
      log_level: '{{ .Values.config.logging.log_level }}'
    alert_proxy_config:
      alert_verification: {{ .Values.config.alert_proxy_config.alert_verification }}
      # Secrets are now sourced from environment variables injected by the Deployment.
      core_account_id: "${CORE_ACCOUNT_NUMBER}"
      core_overseer_id: "${OVERSEER_CORE_DEVICE_ID}"
      account_secret: "${ACCOUNT_SERVICE_TOKEN}"
      am_v2_base_url: "${ALERT_MANAGER_BASE_URL}"
