#   ___  _           _  ______
#  / _ \| |         | | | ___ \
# / /_\ \ | ___ _ __| |_| |_/ / __ _____  ___   _
# |  _  | |/ _ \ '__| __|  __/ '__/ _ \ \/ / | | |
# | | | | |  __/ |  | |_| |  | | | (_) >  <| |_| |
# \_| |_/_|\___|_|   \__\_|  |_|  \___/_/\_\\__, |
#                    Alert-Proxy             __/ |
#                                           |___/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alert-proxy.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alert-proxy.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alert-proxy.selectorLabels" . | nindent 6 }}
      app: alert-proxy
  template:
    metadata:
      labels:
        {{- include "alert-proxy.selectorLabels" . | nindent 8 }}
        app: alert-proxy
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ .name }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: ubuntu
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["/bin/bash", "-c", "while true; do sleep 3600; done"]
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env: # Re-added: Injecting secrets as environment variables from existing Secrets
        - name: CORE_ACCOUNT_NUMBER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.coreAccountId.name }}
              key: {{ .Values.secrets.coreAccountId.key }}
        - name: OVERSEER_CORE_DEVICE_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.overseerDeviceId.name }}
              key: {{ .Values.secrets.overseerDeviceId.key }}
        - name: ACCOUNT_SERVICE_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.accountServiceToken.name }}
              key: {{ .Values.secrets.accountServiceToken.key }}
        - name: ALERT_MANAGER_BASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.alertManagerBaseUrl.name }}
              key: {{ .Values.secrets.alertManagerBaseUrl.key }}
        volumeMounts:
        {{- if .Values.pvc.enabled }}
        - name: alert-proxy-volume
          mountPath: /opt/alert-proxy/logs
        {{- end }}
        - name: config-volume
          mountPath: /opt/alert-proxy/config/config.yaml
          subPath: config.yaml
          readOnly: true
        {{- with .Values.volumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      {{- if .Values.pvc.enabled }}
      - name: alert-proxy-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvc.name }}
      {{- end }}
      - name: config-volume
        configMap:
          name: {{ include "alert-proxy.fullname" . }}-config
      {{- with .Values.volumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
