apiVersion: v1
kind: Service
metadata:
  name: {{ include "alert-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "alert-proxy.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "alert-proxy.selectorLabels" . | nindent 4 }}
    app: alert-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
